name: Aggregate embedding results

on:
  push:
    branches:
      - master
    paths:
      - "experiments/results/*.md"
  workflow_dispatch:
    inputs:
      input_folder:
        description: "Folder to watch for .md files"
        default: "experiments/results"
        required: true

jobs:
  aggregate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown

      - name: Run embeddings aggregator
        run: python experiments/utils/embeddings_results_aggregator.py

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Commit and push cleanup
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git add docs/experiments/embeddings_comparison_results_aggregated.html
          git diff --quiet && git diff --staged --quiet || git commit -m "[Auto-commit] Embedding comparison results update [skip ci]"

          RETRIES=10
          for i in $(seq 1 $RETRIES); do
            git pull --rebase
            git push https://x-access-token:$PAT_TOKEN@github.com/${{ github.repository }} HEAD:master && break || {
              echo "Push failed, retrying ($i/$RETRIES)..."
              sleep 3
            }
          done
