name: Auto-preprocess newly scraped data

on:
  push:
    branches:
      - master
    paths:
      - 'data/raw/*.jsonl'
  workflow_dispatch:

jobs:
  preprocess-and-commit:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Poetry
        run: python -m pip install --upgrade poetry==2.2.0
  
      - name: Install dependencies
        run: |
          poetry install
  
      - name: Run preprocessing
        run: poetry run python ./scripts/preprocess_data.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ./data/processed/
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update preprocessed data"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }} HEAD:master

      